version: '3.8'

services:
  azt-stock-exchange:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3001
      - TESTING_MODE=TRUE
    restart: unless-stopped
