@echo off
echo 🏭 Starting AZT Stock Exchange (Production Mode)...
echo.

echo 📦 Installing dependencies...
npm run install:all

echo 🔨 Building frontend...
npm run build

echo 🚀 Starting combined server...
npm start
